package pl.skeleton.composites;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.themes.Reindeer;

public class RegisterForm extends CustomComponent {
	private static final long serialVersionUID = -3466003893911944834L;
	
	@AutoGenerated
	private HorizontalLayout mainLayout;
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private FormLayout editorLayout = new FormLayout();
	private FieldGroup editorFields = new FieldGroup();
	
	public RegisterForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		buildEditor();
	}

	private void buildEditor() {
		editorLayout.setMargin(false);
		
		TextField loginField = new TextField("Login: ");
			editorLayout.addComponent(loginField);
			loginField.setWidth("100%");
			//editorFields.bind(loginField, propertyId);
		PasswordField passwordField = new PasswordField("Password: ");
			editorLayout.addComponent(passwordField);
		TextField nameField = new TextField("Name: ");
			editorLayout.addComponent(nameField);
		TextField surnameField = new TextField("Surname: ");
			editorLayout.addComponent(surnameField);
		TextField emailField = new TextField("e-mail: ");
			editorLayout.addComponent(emailField);
		TextField cellPhoneField = new TextField("Cell phone: ");
			editorLayout.addComponent(cellPhoneField);
		
		editorLayout.setSizeFull();
		mainLayout.addComponent(editorLayout);
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.addStyleName(Reindeer.WINDOW_BLACK);
		mainLayout.addStyleName("login-layout");
		mainLayout.setSizeFull();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		setSizeFull();
		
		return mainLayout;
	}

}
